#BestPictureWinners
SELECT ?filmLabel ?duration ?directorLabel ?film ?gender_of_directorLabel
WHERE 
{
  ?film wdt:P31 wd:Q11424. #is a film
  ?BestPicture wdt:P279? wd:Q102427 . # P279: subclass of
  ?film wdt:P166? ?BestPicture .            # <- movies that won best picture
  ?film wdt:P2047 ?duration.
      OPTIONAL {?film wdt:P57 ?director.
               ?film wdt:P2047 ?duration.
               ?director wdt:P21 ?gender_of_director.}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}